# Generated by Django 4.0.1 on 2022-03-03 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Core Subjects', (('DS', 'DS'), ('DBMS', 'DBMS'), ('OS', 'OS'), ('COA', 'COA'), ('CN', 'CN'), ('DF', 'DF'), ('SE', 'SE'))), ('Language specific', (('C', 'C'), ('JAVA', 'JAVA'), ('PHP', 'PHP'), ('PYTHON', 'PYTHON')))], default='DS', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('note', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='static/dashmin/img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
