# Generated by Django 4.0.1 on 2022-03-04 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashmin', '0002_forms_delete_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'forms', 'verbose_name_plural': 'forms'},
        ),
        migrations.AlterField(
            model_name='forms',
            name='file',
            field=models.FileField(upload_to='static/dashmin/file/'),
        ),
        migrations.CreateModel(
            name='Videoform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('caption', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static/dashmin/video/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Videoforms',
                'verbose_name_plural': 'Videoforms',
            },
        ),
    ]
