# Generated by Django 4.0.1 on 2022-03-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0003_alter_forms_options_alter_forms_file_videoform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoform',
            options={'verbose_name': 'Videoform', 'verbose_name_plural': 'Videoform'},
        ),
        migrations.RemoveField(
            model_name='forms',
            name='file',
        ),
    ]
