# Generated by Django 4.0.1 on 2022-03-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashmin', '0004_alter_videoform_options_remove_forms_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdfforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('note', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='static/dashmin/%y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pdfforms',
                'verbose_name_plural': 'Pdfforms',
            },
        ),
        migrations.DeleteModel(
            name='Forms',
        ),
    ]
