# Generated by Django 4.0.1 on 2022-03-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0005_pdfforms_delete_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoform',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pdfforms',
        ),
        migrations.DeleteModel(
            name='Videoform',
        ),
    ]
