# Generated by Django 4.0.1 on 2022-03-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0008_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesform',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='NotesForm',
        ),
    ]
