# Generated by Django 4.0.1 on 2022-03-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteforms',
            name='file',
        ),
    ]
