# Generated by Django 4.0.1 on 2022-03-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0012_noteform_delete_noteforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
