# Generated by Django 4.0.1 on 2022-03-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0013_ex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ex',
            new_name='Note1',
        ),
        migrations.DeleteModel(
            name='NoteForm',
        ),
    ]
