# Generated by Django 4.0.1 on 2022-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0015_alter_note1_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note2',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('add', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Note1',
        ),
    ]
