# Generated by Django 4.0.1 on 2022-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0017_note3_delete_note2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note3',
            name='file',
            field=models.ImageField(upload_to='file'),
        ),
    ]
