# Generated by Django 4.0.1 on 2022-03-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0018_alter_note3_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note3',
        ),
    ]
