# Generated by Django 4.0.1 on 2022-03-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0021_noteforms_delete_notesform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteForms',
            new_name='NoteForm',
        ),
    ]
