# Generated by Django 4.0.1 on 2022-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0023_alter_noteform_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('DS', 'DS'), ('OS', 'OS'), ('DBMS', 'DBMS'), ('COA', 'COA'), ('DF', 'DF'), ('CN', 'CN'), ('C', 'C'), ('JAVA', 'JAVA'), ('PHP', 'PHP'), ('PYTHON', 'PYTHON')], max_length=20)),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('video', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='videos')),
                ('link1', models.URLField(default=False, max_length=300)),
            ],
            options={
                'verbose_name': 'VideoForm',
                'verbose_name_plural': 'VideoForm',
            },
        ),
    ]
