# Generated by Django 4.0.1 on 2022-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0025_alter_videoform_file_alter_videoform_link1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoform',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='videoform',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='videoform',
            name='link1',
            field=models.URLField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
