# Generated by Django 4.0.1 on 2022-04-04 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashmin', '0027_edit_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='edit_profile',
            new_name='edit_user',
        ),
    ]
