# Generated by Django 4.0.1 on 2022-04-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashmin', '0030_editprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='editProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('subarea', models.CharField(max_length=20)),
                ('Profile', models.CharField(max_length=300)),
                ('file', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='editProfile',
        ),
    ]
