# Generated by Django 4.0.1 on 2022-04-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0031_editprofiles_delete_editprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editprofiles',
            options={'verbose_name': 'Edit Profile', 'verbose_name_plural': 'Edit Profile'},
        ),
        migrations.RenameField(
            model_name='editprofiles',
            old_name='file',
            new_name='pic',
        ),
    ]
