# Generated by Django 4.0.1 on 2022-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0034_alter_editprofiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofiles',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
