# Generated by Django 4.0.1 on 2022-04-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0035_alter_editprofiles_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editProfiles',
        ),
    ]
