# Generated by Django 4.0.1 on 2022-04-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0036_delete_editprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('subarea', models.CharField(max_length=20)),
                ('Profile', models.CharField(max_length=300)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
            ],
            options={
                'verbose_name': 'user_edit',
                'verbose_name_plural': 'user_edit',
            },
        ),
    ]
